import {describe,it,expect,vi} from 'vitest';
import {createClaudeChatHandler,type ClaudeChatDeps} from '../../supabase/functions/claude-chat/handler';
const setup=():ClaudeChatDeps=>({verifyOwner:vi.fn().mockResolvedValue(true),readKey:vi.fn().mockResolvedValue('private-vault-key'),reserve:vi.fn().mockResolvedValue('reservation'),settle:vi.fn().mockResolvedValue(undefined),fetch:vi.fn()});
const req=(body:unknown,token='owner')=>new Request('https://office.test/claude-chat',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:JSON.stringify(body)});
describe('Vault-backed Claude endpoint',()=>{
 it('refuses a non-owner before reading Vault or calling a provider',async()=>{const d=setup();vi.mocked(d.verifyOwner).mockResolvedValue(false);expect((await createClaudeChatHandler(d)(req({prompt:'hello',model:'chosen-model'}))).status).toBe(401);expect(d.readKey).not.toHaveBeenCalled();expect(d.fetch).not.toHaveBeenCalled();});
 it('rejects system messages, empty prompts and oversized inputs before reading a key',async()=>{for(const input of [{messages:[{role:'system',content:'x'}],model:'chosen-model'},{prompt:'',model:'chosen-model'},{prompt:'x'.repeat(12001),model:'chosen-model'},null]){const d=setup();expect((await createClaudeChatHandler(d)(req(input))).status).toBe(400);expect(d.readKey).not.toHaveBeenCalled();}});
 it('checks available models without a paid reservation and returns no credential',async()=>{const d=setup();vi.mocked(d.fetch).mockResolvedValue(new Response(JSON.stringify({data:[{id:'chosen-model',display_name:'Chosen model'}]})));const r=await createClaudeChatHandler(d)(req({action:'models'}));expect(await r.json()).toEqual({ok:true,models:[{id:'chosen-model',name:'Chosen model'}],hasMore:false});expect(d.reserve).not.toHaveBeenCalled();});
 it('fails closed when the office budget denies the call',async()=>{const d=setup();vi.mocked(d.reserve).mockResolvedValue(null);expect((await createClaudeChatHandler(d)(req({prompt:'hello',model:'chosen-model'}))).status).toBe(429);expect(d.fetch).not.toHaveBeenCalled();});
 it('sends the Vault key only as an upstream header and settles a real-shaped reply',async()=>{const d=setup();vi.mocked(d.fetch).mockResolvedValue(new Response(JSON.stringify({content:[{type:'text',text:'A code suggestion'}],model:'chosen-model',stop_reason:'end_turn'})));const r=await createClaudeChatHandler(d)(req({prompt:'hello',model:'chosen-model'}));expect(await r.json()).toMatchObject({ok:true,text:'A code suggestion',complete:true});const [url,init]=vi.mocked(d.fetch).mock.calls[0]!;expect(url).toBe('https://api.anthropic.com/v1/messages');expect(init?.headers).toMatchObject({'x-api-key':'private-vault-key'});expect(init?.body).not.toContain('private-vault-key');expect(init?.body).not.toContain('owner');expect(d.settle).toHaveBeenCalledWith('owner','reservation','ok');});
 it('sanitizes provider failures and settles the attempt',async()=>{const d=setup();vi.mocked(d.fetch).mockResolvedValue(new Response('private-vault-key',{status:401}));const r=await createClaudeChatHandler(d)(req({prompt:'hello',model:'chosen-model'}));expect(await r.text()).not.toContain('private-vault-key');expect(d.settle).toHaveBeenCalledWith('owner','reservation','failed');});
 it('marks token-limited replies incomplete instead of claiming completion',async()=>{const d=setup();vi.mocked(d.fetch).mockResolvedValue(new Response(JSON.stringify({content:[{type:'text',text:'Partial'}],stop_reason:'max_tokens'})));expect(await (await createClaudeChatHandler(d)(req({prompt:'hello',model:'chosen-model'}))).json()).toMatchObject({ok:true,complete:false});});
});
