import {describe,it,expect,vi} from 'vitest';
import {claudeBuildsWith,CLAUDE_BUILD_MAX_USD,type ClaudeBuildDeps} from './claude-builds.server';
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
const setup=():ClaudeBuildDeps=>({enabled:true,githubToken:'private-key',maxBudgetUsd:1,verify:vi.fn().mockResolvedValue({ok:true,userId:'owner',aal:'aal2',email:''}),fetch:vi.fn()});
describe('Claude office build bridge',()=>{
 it('reports the server budget in a read-only status check',async()=>{const d={...setup(),maxBudgetUsd:CLAUDE_BUILD_MAX_USD};vi.mocked(d.fetch).mockResolvedValue(json({workflow_runs:[]}));const r=await claudeBuildsWith(d,'owner');expect(r.detail).toContain('Claude API budget limit: US$2.00 per build.');expect(d.fetch).toHaveBeenCalledOnce();expect(vi.mocked(d.fetch).mock.calls[0]![1]?.body).toBeUndefined();});
 it('requires owner verification before any GitHub access',async()=>{const d=setup();vi.mocked(d.verify).mockResolvedValue({ok:false,reason:'mfa_required',message:'Verify owner'});expect((await claudeBuildsWith(d,'bad','Build a better room')).ok).toBe(false);expect(d.fetch).not.toHaveBeenCalled();});
 it('requires explicit enablement and an approved spending cap',async()=>{for(const value of [{enabled:false},{maxBudgetUsd:undefined},{maxBudgetUsd:11}]){const d={...setup(),...value};expect((await claudeBuildsWith(d,'owner','Build a better room')).ok).toBe(false);expect(d.fetch).not.toHaveBeenCalled();}});
 it('dispatches only the Claude workflow with request and bounded spend, without owner credentials',async()=>{const d={...setup(),maxBudgetUsd:CLAUDE_BUILD_MAX_USD};vi.mocked(d.fetch).mockResolvedValueOnce(json({workflow_runs:[]})).mockResolvedValueOnce(json({workflow_run_id:77}));const r=await claudeBuildsWith(d,'owner-secret','Build a clearer room');expect(r.runs?.[0]?.id).toBe(77);const [url,init]=vi.mocked(d.fetch).mock.calls[1]!;expect(url).toBe('https://api.github.com/repos/canericaextreme/CanX-Office/actions/workflows/canx-claude.yml/dispatches');expect(JSON.parse(String(init?.body))).toEqual({ref:'main',inputs:{request:'Build a clearer room',max_budget_usd:'2'}});expect(init?.body).not.toContain('owner-secret');});
 it('does not duplicate a paid job while another Claude build is active',async()=>{const d=setup();vi.mocked(d.fetch).mockResolvedValue(json({workflow_runs:[{id:1,status:'in_progress'}]}));expect((await claudeBuildsWith(d,'owner','Build a better room')).ok).toBe(false);expect(d.fetch).toHaveBeenCalledOnce();});
 it('does not accept evidence from Codex or other workflows',async()=>{const d=setup();vi.mocked(d.fetch).mockResolvedValue(json({id:77,path:'.github/workflows/canx-codex.yml',event:'workflow_dispatch'}));expect((await claudeBuildsWith(d,'owner',undefined,undefined,77)).ok).toBe(false);});
 it('reports an uncertain dispatch without retrying or exposing secrets',async()=>{const d=setup();vi.mocked(d.fetch).mockResolvedValueOnce(json({workflow_runs:[]})).mockRejectedValueOnce(Error('private-key'));const r=await claudeBuildsWith(d,'owner','Build a better room');expect(r.detail).toContain('may already be running');expect(r.detail).not.toContain('private-key');expect(d.fetch).toHaveBeenCalledTimes(2);});
});

