/** Room purposes; descriptions do not imply that planned connections are live. */
export const ROOM_SYNOPSES: Record<string, string> = {
  '/reception': 'Reception is the starting point for the Office, where you explain what you need and speak with Elsie. It helps you find the right room and decide the next step.',
  '/owner-desk': 'The Owner’s Desk brings together your priorities, pending approvals, budget and recent changes. It gives you a place to review what needs your attention and direct the Office’s work.',
  '/family-continuity': 'Family Continuity & Training is for preserving family knowledge, important records and clear instructions for running the Office. Its access rules and working skills still need to be connected before it can guide a family handover.',
  '/office-team': 'Office Team shows the people and AI roles intended to support the Office. It lets you review responsibilities and distinguish connected workers from helpers that are still planned.',
  '/health': 'Office Health is the room for reliability, warnings, capacity, backup and recovery. Its purpose is to help you spot problems and keep the Office dependable as monitoring is connected.',
  '/approvals': 'Approvals collects requests that need an owner’s decision before work proceeds. You can review the reason, risks and proposed action, then record an approval or rejection.',
  '/communications': 'Communications & Marketing is the home for correspondence, messages and plans to reach customers. It is intended to organize launches, ads, posts and results; mailbox and campaign connections still need to be added.',
  '/idea-garage': 'Idea Garage is where you capture and explore new ideas before turning them into projects. It helps you consider demand, feasibility, costs and next steps, or park an idea for later.',
  '/systems': 'Systems keeps track of the services, accounts and connections the Office depends on. It helps you check what is actually connected and plan access, backup and recovery.',
  '/blueprint': 'Blueprint records how the Office is designed and the decisions behind that design. It is a reference for room purposes, architecture and planned changes as the Office develops.',
  '/research': 'Research is for gathering evidence, checking sources and comparing options before a decision. The room and file collection are available, while its research skills and live work areas still need connecting.',
  '/legal': 'Legal is the place for contracts, obligations, privacy, ownership and compliance questions. It organizes matters needing review and supporting records, with professional advice used when required.',
  '/work-board': 'Work Board tracks tasks, responsibility, priorities and blockers. It helps you see what is planned, assigned, waiting or complete, including what a waiting task needs next.',
  '/subscriptions': 'Subscriptions keeps an inventory of the services and AI providers used by the Office. It helps you review costs, renewals and connection evidence so you can manage spending and access.',
  '/records': 'Records is the place for keeping files, decisions and supporting sources organized. It provides a reference point for the evidence and history behind the Office’s work.',
  '/finance': 'Finance holds private receipts, financial records and spending reviews behind an extra security check. It helps you inspect imported receipts and totals, then review reconciliation and budget needs.',
  '/safe-highways': 'Safe Highways is the Office’s home for highway-safety projects and programme oversight. It is intended to bring reporting, standards and routing work together as the project’s data connections are added.',
  '/future': 'Future is for longer-term plans, retirement goals and possible Office expansion. It gives you somewhere to keep the direction you want to take beyond today’s tasks.',
  '/build-testing': 'Build & Testing is for preparing project briefs, checking changes and planning releases. Its current planning examples are separate from live build or deployment results.',
  '/brain': 'CanX Brain keeps shared records, handovers and original files for the Office. Existing memory records can support Elsie, while newly uploaded files still need processing before their contents become searchable knowledge.',
  '/analytics': 'Analytics Control Wall is the place for business graphs and trends, including revenue, expenses, workload and progress. Live charts still need data connections; reliability and recovery belong in Office Health.',
  '/projects': 'Project Rooms brings together the projects the Office is working toward. It is intended to organize each project’s goals, tasks and progress; the current project examples are planning material.',
  '/skills': 'Skills defines the instructions, capabilities and approval boundaries each room needs to do its job. It provides a place to review what is allowed and what still needs to be connected and tested.',
  '/round-table': 'Round Table brings priorities, research questions and decisions into a shared review. It organizes the agenda, meeting notes and follow-up actions; planned seats do not represent connected participants.',
};
