import { OfficeFilePreview } from "./OfficeFilePreview";
import { OfficeFileThumbnail } from "./OfficeFileThumbnail";
import { useEffect, useRef, useState } from 'react';
import { useServerFn } from '@tanstack/react-start';
import { useOwnerSession } from '@/lib/owner-session';
import { FILE_BUCKET, FILE_FOLDERS, FILE_ROOMS, MAX_FILE_BYTES, type OfficeFile } from '@/lib/office-files';
import { prepareOfficeUpload, finishOfficeUpload, listOfficeFiles, openOfficeFile, officeUploadConnection, saveOfficeLink, deleteOfficeFile } from '@/lib/office-files.functions';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Plus, X } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
export function OfficeFiles({room='brain',compact=false,collapseList=false,onSaved}:{room?:string;compact?:boolean;collapseList?:boolean;onSaved?:(file:OfficeFile)=>void}) {
 const session=useOwnerSession(); const prepare=useServerFn(prepareOfficeUpload); const finish=useServerFn(finishOfficeUpload); const list=useServerFn(listOfficeFiles); const openFile=useServerFn(openOfficeFile); const connection=useServerFn(officeUploadConnection); const saveLink=useServerFn(saveOfficeLink); const deleteFile=useServerFn(deleteOfficeFile);
 const [deleteTarget,setDeleteTarget]=useState<OfficeFile|null>(null); const [deleting,setDeleting]=useState(false); const [deleteError,setDeleteError]=useState('');
 const [previewFile,setPreviewFile]=useState<OfficeFile|null>(null); const [savedMessage,setSavedMessage]=useState('');
 const [destination,setDestination]=useState(room); const [folder,setFolder]=useState(room==='finance'?'Finance':room==='family-continuity'?'Family and Legacy':'CanX Projects'); const [files,setFiles]=useState<OfficeFile[]>([]); const [selected,setSelected]=useState<File[]>([]); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false); const [show,setShow]=useState(false); const [refresh,setRefresh]=useState(0); const picker=useRef<HTMLInputElement>(null); const [linkUrl,setLinkUrl]=useState(''); const [linkTitle,setLinkTitle]=useState(''); const activeToken=useRef(session.accessToken); activeToken.current=session.accessToken;
 useEffect(()=>{setDestination(room);},[room]);
 useEffect(()=>{let active=true;setFiles([]); if(session.accessToken && (!compact||show)) void list({data:{accessToken:session.accessToken,room:compact?destination:room}}).then(rows=>{if(active)setFiles(rows);}).catch(e=>{if(active)setStatus(e instanceof Error?e.message:'Files unavailable.');}); return()=>{active=false;};},[session.accessToken,list,room,destination,compact,show,refresh]);
 async function upload(){const accessToken=session.accessToken;if(!accessToken||busy)return;setBusy(true);setSavedMessage('');let saved=0;
  try {const config=await connection({data:{accessToken}});const {createClient}=await import('@supabase/supabase-js');const db=createClient(config.url,config.key,{global:{headers:{Authorization:`Bearer ${accessToken}`}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
   for(const file of selected){if(activeToken.current!==accessToken)throw new Error('Sign-in changed. Sign in again to continue.');if(!file.size||file.size>MAX_FILE_BYTES)throw new Error(`${file.name}: choose a file up to 25 MB.`);setStatus(`Saving ${file.name}…`);
    const buffer=await file.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',buffer);const hash=Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,'0')).join('');
    const input={accessToken,filename:file.name,room:destination,folder,size_bytes:file.size,content_hash:hash,mime_type:file.type||'application/octet-stream'};
    const prepared=await prepare({data:input});if(prepared.uploadToken){const {error}=await db.storage.from(FILE_BUCKET).uploadToSignedUrl(prepared.path,prepared.uploadToken,file,{contentType:input.mime_type});if(error)throw new Error(`${file.name}: upload failed. Retry the same file.`);}
    const record=await finish({data:input});saved++;setSavedMessage(`Uploaded into ${FILE_ROOMS.find(r=>r.id===destination)?.label} → ${folder}: ${file.name}`);onSaved?.(record);setSelected(current=>current.filter(f=>f!==file));setRefresh(n=>n+1);
   }setStatus(`Saved ${saved} file${saved===1?'':'s'} in ${FILE_ROOMS.find(r=>r.id===destination)?.label} → ${folder}. Private to your owner account.`);
  }catch(e){setStatus(`${saved?`${saved} file(s) saved. `:''}${e instanceof Error?e.message:'Save was not confirmed.'}`);}finally{setBusy(false);}
 }
 async function download(file:OfficeFile){if(!session.accessToken)return;try{const url=await openFile({data:{accessToken:session.accessToken,id:file.id,download:true}});window.location.assign(url);}catch(e){setStatus(e instanceof Error?e.message:'File unavailable.');}}
 async function addLink(){if(!session.accessToken||busy)return;setBusy(true);try{const record=await saveLink({data:{accessToken:session.accessToken,url:linkUrl,title:linkTitle,room:destination,folder}});onSaved?.(record);setLinkUrl('');setLinkTitle('');setRefresh(n=>n+1);setStatus('Web link saved. The linked page or file was not downloaded.');}catch(e){setStatus(e instanceof Error?e.message:'Link save was not confirmed.');}finally{setBusy(false);}}
 async function removeSavedFile(){const accessToken=session.accessToken;if(!accessToken||!deleteTarget||deleting)return;const target=deleteTarget;setDeleting(true);setDeleteError('');try{await deleteFile({data:{accessToken,id:target.id,kind:target.source_url?'link':'file'}});if(activeToken.current!==accessToken)return;setFiles(current=>current.filter(f=>f.id!==target.id));if(previewFile?.id===target.id)setPreviewFile(null);setSavedMessage('');setStatus(`Deleted from the Office: ${target.filename}`);setDeleteTarget(null);setRefresh(n=>n+1);}catch(e){setDeleteError(e instanceof Error?e.message:'Deletion was not confirmed.');}finally{setDeleting(false);}}
 const savedList=<SavedFileList files={files} room={room} sessionKey={`${session.ownerId}:${session.aal}:${session.signedIn}`} accessToken={session.accessToken} disabled={busy||deleting} onOpen={f=>{setShow(false);setPreviewFile(f);}} onDelete={f=>{setDeleteError('');setShow(false);setDeleteTarget(f);}}/>;
 return <div className={compact?'':'mb-5 space-y-3'}>
  <Dialog open={show} onOpenChange={setShow}><DialogTrigger asChild><Button variant="outline" size="sm"><Plus className="h-4 w-4"/> Add files or photos</Button></DialogTrigger>
   <DialogContent className="max-h-[85dvh] overflow-y-auto"><DialogHeader><DialogTitle>Add files, photos or videos</DialogTitle></DialogHeader>
    {savedMessage&&<p role="status" className="rounded border border-green-500 bg-green-950/20 p-3 font-medium text-green-600 dark:text-green-300">{savedMessage}</p>}
    <label className="text-sm">File in room<select className="mt-1 w-full rounded border bg-background p-2" disabled={busy} value={destination} onChange={e=>setDestination(e.target.value)}>{FILE_ROOMS.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label>
    <label className="text-sm">Folder<select className="mt-1 w-full rounded border bg-background p-2" disabled={busy} value={folder} onChange={e=>setFolder(e.target.value)}>{FILE_FOLDERS.map(f=><option key={f}>{f}</option>)}</select></label>
    <p className="text-sm font-medium">Upload from your computer</p><Button variant="outline" disabled={busy||!session.accessToken} onClick={()=>picker.current?.click()}>Choose from computer</Button>
    <input ref={picker} className="sr-only" aria-label="Choose files, photos or videos" type="file" multiple disabled={busy||!session.accessToken} onChange={e=>{setSelected(Array.from(e.target.files??[]));e.target.value='';}}/>
    <p className="text-sm">Original files stay intact and private. Up to 25 MB per file. Saving does not share a file or ask Elsie to analyze it.</p>
    {destination==='approvals'&&<p className="text-sm">These are supporting files. Saving does not create or approve a decision request.</p>}
    {selected.map((f,i)=><p key={`${f.name}-${i}`} className="text-sm break-words">{f.name}</p>)}
    <Button disabled={busy||!selected.length||!session.accessToken} onClick={()=>void upload()}>{busy?'Saving…':'Save selected files'}</Button><div className="border-t pt-3 space-y-2"><p className="text-sm font-medium">Or save a web link</p><input className="w-full rounded border bg-background p-2" aria-label="Web link" type="url" placeholder="https://…" disabled={busy} value={linkUrl} onChange={e=>setLinkUrl(e.target.value)}/><input className="w-full rounded border bg-background p-2" aria-label="Link title" placeholder="Title (optional)" disabled={busy} value={linkTitle} onChange={e=>setLinkTitle(e.target.value)}/><Button variant="outline" disabled={busy||!session.accessToken||!linkUrl.trim()} onClick={()=>void addLink()}>Save web link</Button><p className="text-sm">Saves the address for later. It does not copy the website or download its files.</p></div><p role="status" className="text-sm">{status}</p>{compact&&savedList}
   </DialogContent></Dialog>
  <Dialog open={!!deleteTarget} onOpenChange={open=>{if(!open&&!deleting)setDeleteTarget(null);}}><DialogContent><DialogHeader><DialogTitle>Delete this saved entry?</DialogTitle></DialogHeader><p className="break-words font-medium">{deleteTarget?.filename}</p><p className="text-sm text-muted-foreground">{FILE_ROOMS.find(r=>r.id===deleteTarget?.room)?.label} · {deleteTarget?.folder}</p><p className="text-sm">This removes this entry from the Office. Other saved entries and the original on your computer stay unchanged.{!deleteTarget?.source_url&&' The uploaded original remains in private storage because other entries may use it.'}</p>{deleteError&&<p role="alert" className="text-sm text-destructive">{deleteError}</p>}<div className="flex justify-end gap-2"><Button variant="outline" disabled={deleting} onClick={()=>setDeleteTarget(null)}>Cancel</Button><Button variant="destructive" disabled={deleting||!session.accessToken} onClick={()=>void removeSavedFile()}>{deleting?'Deleting…':'Delete'}</Button></div></DialogContent></Dialog>
  <OfficeFilePreview file={previewFile} accessToken={session.accessToken} onClose={()=>setPreviewFile(null)} onDownload={file=>void download(file)}/>
  {!compact&&!collapseList&&<section aria-label="Saved files" className="rounded-xl border border-border bg-card p-4 space-y-3">{savedMessage&&<p role="status" className="rounded border border-green-500 bg-green-950/20 p-3 font-medium text-green-600 dark:text-green-300">{savedMessage}</p>}<p role="status" className="text-sm">{status}</p>{savedList}</section>}
  {!compact&&collapseList&&<>{status&&<p role="status" className="text-sm">{status}</p>}<details className="rounded-xl border border-border bg-card p-3"><summary className="cursor-pointer text-sm font-medium">Open, preview or delete uploaded files{files.length?` (${files.length===200?'showing up to 200':files.length})`:''}</summary><div className="mt-3">{savedList}</div></details></>}
 </div>;
}

/** Populated saved-files list. Exported so post-update health checks can render it with realistic fixtures. */
export function SavedFileList({files,room,sessionKey,accessToken,disabled,onOpen,onDelete}:{files:OfficeFile[];room:string;sessionKey:string;accessToken:string|null|undefined;disabled:boolean;onOpen:(f:OfficeFile)=>void;onDelete:(f:OfficeFile)=>void}) {
 return <div className="space-y-3">{files.length===200&&<p className="text-sm">Showing the 200 most recent files.</p>}{files.map(f=><div key={f.id} className="flex items-center justify-between gap-3 rounded border border-border p-3"><div className="min-w-0"><p className="break-words font-medium">{f.filename}</p><p className="text-sm text-muted-foreground">{FILE_ROOMS.find(r=>r.id===f.room)?.label} · {f.folder} · {f.source_url ? 'Web link' : `${(f.size_bytes/1024/1024).toFixed(1)} MB`}</p></div><div className="flex shrink-0 items-center gap-2"><OfficeFileThumbnail key={`${f.id}:${sessionKey}`} file={f} accessToken={accessToken}/>{f.source_url ? <Button asChild variant="outline" size="sm"><a href={f.source_url} target="_blank" rel="noopener noreferrer">Open link</a></Button> : <Button variant="outline" size="sm" onClick={()=>onOpen(f)}>Open file</Button>}{room==='brain'&&<TooltipProvider><Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon" aria-label={`Delete ${f.filename}`} disabled={disabled||!accessToken} onClick={()=>onDelete(f)}><X className="h-4 w-4"/></Button></TooltipTrigger><TooltipContent>Delete</TooltipContent></Tooltip></TooltipProvider>}</div></div>)}</div>;
}
