/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfficeRouteImport } from './routes/_office'
import { Route as OfficeIndexRouteImport } from './routes/_office/index'

const OfficeRoute = OfficeRouteImport.update({
  id: '/_office',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof OfficeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof OfficeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_office': typeof OfficeRouteWithChildren
  '/_office/': typeof OfficeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_office' | '/_office/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OfficeRoute: typeof OfficeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_office': {
      id: '/_office'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_office/': {
      id: '/_office/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
  }
}

interface OfficeRouteChildren {
  OfficeIndexRoute: typeof OfficeIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeIndexRoute: OfficeIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OfficeRoute: OfficeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
